name = "simple"
license = "MIT"
description = "simple: simple is a simple package."
homepage = "https://github.com/ajuancer/juancer.me"
tags = ["Hugo", "Tailwind CSS", "theme", "starter", "boilerplate"]
features = []
min_version = "0.69"

[author]
  name = "Juan Cerde√±o"
  homepage = "https://juancer.me/"
